model:
  target: Models.interpretable_diffusion.FMTS.FM_TS
  params:
    seq_length: 128
    feature_size: 1
    n_layer_enc: 4
    n_layer_dec: 3
    d_model: 96
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-4
  max_epochs: 4001
  gradient_accumulate_every: 1
  save_cycle: 200
  ema:
    decay: 0.995
    update_interval: 10

dataloader:
  train_dataset:
    target: Utils.Data_utils.repo_dataset.RepoWindowDataset
    params:
      name: ercot
      datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
      data_name: ErcotData
      rel_path: ERCOT_merged.csv
      window: 128
      stride: 1
      period: train
      save2npy: true

  val_dataset:
    target: Utils.Data_utils.repo_dataset.RepoWindowDataset
    params:
      name: ercot
      datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
      data_name: ErcotData
      rel_path: ERCOT_merged.csv
      window: 128
      stride: 1
      period: valid
      save2npy: true

  batch_size: 512
  sample_size: 512
  shuffle: true
