model:
  target: Models.interpretable_diffusion.FMTS.FM_TS
  params:
    seq_length: 512
    feature_size: 1
    n_layer_enc: 4
    n_layer_dec: 3
    d_model: 64
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-4
  max_epochs: 1001
  gradient_accumulate_every: 1
  save_cycle: 100
  ema:
    decay: 0.995
    update_interval: 10

dataloader:
  train_dataset:
    target: Utils.Data_utils.repo_dataset.RepoWindowDataset
    params:
      name: glucosesliding
      datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
      data_name: GlucoseSliding
      rel_path_train: glucose_train.parquet
      rel_path_valid: glucose_valid.parquet
      window: 512
      stride: 128
      period: train
      save2npy: true

  val_dataset:
    target: Utils.Data_utils.repo_dataset.RepoWindowDataset
    params:
      name: glucosesliding
      datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
      data_name: GlucoseSliding
      rel_path_train: glucose_train.parquet
      rel_path_valid: glucose_valid.parquet
      window: 512
      stride: 128
      period: valid
      save2npy: true

  batch_size: 512
  sample_size: 512
  shuffle: true
