# training:
epochs: 1001
batch_size: 512
learning_rate: 0.0001
weight_decay: 0.00001
# logging:
logging_iter: 100
tags: []
run_dir: FlowTS/GlucoseSliding_len256/
# Data
datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
seq_len: 256
pretrain: false
datasets:
  - name: GlucoseSliding
    data: GlucoseSliding
    rel_path_train: glucose_train.parquet
    rel_path_valid: glucose_valid.parquet
    stride: 128
train_on_datasets:
  - GlucoseSliding

handler: models.FlowTS.handler
model:
  target: models.interpretable_diffusion_flowts.FMTS.FM_TS
  params:
    seq_length: 256
    feature_size: 1
    n_layer_enc: 4
    n_layer_dec: 3
    d_model: 64
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-4
  max_epochs: 1001
  gradient_accumulate_every: 1
  save_cycle: 100
  ema:
    decay: 0.995

dataloader:
  train_dataset:
    target: data_provider.datasets.glucose_sliding.GlucoseSliding
    params:
      datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
      seq_len: 256
      stride: 128
      rel_path: glucose_train.parquet
      flag: train

  val_dataset:
    target: data_provider.datasets.glucose_sliding.GlucoseSliding
    params:
      datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
      seq_len: 256
      stride: 128
      rel_path: glucose_valid.parquet
      flag: valid

  batch_size: 512
  sample_size: 512
  shuffle: true
