# training:
epochs: 4001
batch_size: 512
learning_rate: 0.0001
weight_decay: 0.00001
# logging:
logging_iter: 100
tags: []
run_dir: FlowTS/HouseholdData_len256/
# Data
datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
seq_len: 256
pretrain: false
datasets:
  - name: HouseholdData
    data: HouseholdData
    rel_path: HouseHold_6.csv
    window_stride: 10
    ts_stride: 10
    stride: 10
train_on_datasets:
  - HouseholdData

handler: models.FlowTS.handler
model:
  target: models.interpretable_diffusion_flowts.FMTS.FM_TS
  params:
    seq_length: 256
    feature_size: 6
    n_layer_enc: 4
    n_layer_dec: 3
    d_model: 96
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-4
  max_epochs: 4001
  gradient_accumulate_every: 1
  save_cycle: 100
  ema:
    decay: 0.995

dataloader:
  train_dataset:
    target: data_provider.datasets.local_timeseries.HouseholdData
    params:
      datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
      rel_path: HouseHold_6.csv
      seq_len: 256
      stride: 10
      flag: train

  val_dataset:
    target: data_provider.datasets.local_timeseries.HouseholdData
    params:
      datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
      rel_path: HouseHold_6.csv
      seq_len: 256
      stride: 10
      flag: valid

  batch_size: 512
  sample_size: 512
  shuffle: true
