# training:
epochs: 4001
batch_size: 512
learning_rate: 0.0001
weight_decay: 0.00001
# transform:
use_stft: false
delay: 24
embedding: 24
# model:
handler: models.ImagenTime.handler
img_resolution: 24
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [8,4,2]
diffusion_steps: 36
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
tags: []
run_dir: ImagenTime/ErcotData_len512/
# Data
datasets_dir: /mnt/unites8/playpen/haochenz/Time_Series_Datasets
seq_len: 512
pretrain: false
datasets:
  - name: ErcotData
    data: ErcotData
    rel_path: ERCOT_merged.csv
    stride: 1
train_on_datasets:
  - ErcotData
