# training:
epochs: 1001
batch_size: 512
learning_rate: 0.0001
weight_decay: 0.00001
# transform:
use_stft: false
delay: 16
embedding: 16
# model:
handler: models.ImagenTime.handler
img_resolution: 16
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [8,4,2]
diffusion_steps: 36
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
tags: []
run_dir: ImagenTime/GlucoseSliding_len128/
# Data
datasets_dir: /playpen-shared/haochenz/AI-READI-Dataset/AI-READI-processed
seq_len: 128
pretrain: false
datasets:
  - name: GlucoseSliding
    data: GlucoseSliding
    rel_path_train: glucose_train.parquet
    rel_path_valid: glucose_valid.parquet
    stride: 128
train_on_datasets:
  - GlucoseSliding
